name: travel
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  sqflite: ^2.3.3+1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: ElMessiri
      fonts:
        - asset: assets/font/ElMessiri-Regular.ttf
        - asset: assets/font/ElMessiri-SemiBold.ttf
          weight: 700
        - asset: assets/font/ElMessiri-Bold.ttf
          weight: 600
    - family: Amiri
      fonts:
        - asset: assets/font/Amiri-Regular.ttf
        - asset: assets/font/Amiri-Bold.ttf
          weight: 700
